群聊学习总开关: true
全局屏蔽词: [ ]
全局屏蔽用户: [ ]
单句关键词分词数量: 3
跨群回复阈值: 2
最高学习次数: 6
自定义词典: [ ]
分群配置:
  719820234:
    群聊学习开关: true
    屏蔽词: [ ]
    屏蔽用户: [ ]
    回复阈值: 4
    回复阈值权重:
      - 10
      - 30
      - 60
    复读阈值: 3
    打断复读概率: 0.25
    主动发言开关: true
    主动发言阈值: 5
    主动发言最小间隔: 300
    连续主动发言概率: 0.5
    最大连续主动发言句数: 3
    主动发言附带戳一戳概率: 0.5
